server.error.whitelabel.enabled=false

spring.datasource.url=jdbc:mysql://localhost:3306/taskdata?zeroDateTimeBehavior=CONVERT_TO_NULL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root

#spring.jpa.properties.hibernate.hbm2ddl.auto=create

taskmanager.app.jwtCookieName=taskdata
taskmanager.app.jwtSecret=secret
taskmanager.app.jwtExpirationMs=30000

file.upload.directory=uploads
